M48
; DRILL file KiCad 10.0.1 date 2026-07-25T14:28:41
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-25T14:28:41+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X73.59Y-133.81
X79.37Y-133.81
T2
X67.75Y-82.75
X67.75Y-137.25
X162.25Y-82.75
X162.25Y-137.25
M30
